# Generated by Django 5.2.10 on 2026-02-17

from django.db import migrations, models


def map_tracklet_status(apps, schema_editor):
    """Map existing stock rows to Tracklet status values."""
    StockItem = apps.get_model('stock', 'StockItem')

    valid_statuses = {'IN_STOCK', 'MISSING', 'BROKEN', 'CALIBRATION', 'REPAIR'}

    # Default mapping
    StockItem.objects.all().update(tracklet_status='IN_STOCK')

    # Preserve compatible custom status keys if they already exist
    for item in StockItem.objects.exclude(status_custom_key__isnull=True):
        key = str(item.status_custom_key).upper()
        if key in valid_statuses:
            item.tracklet_status = key
            item.save(update_fields=['tracklet_status'])


def reverse_tracklet_status(apps, schema_editor):
    """No-op reverse migration for Tracklet status mapping."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0118_auto_20260205_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='last_calibration_date',
            field=models.DateField(
                blank=True,
                help_text='Last calibration date for this stock item',
                null=True,
                verbose_name='Last Calibration',
            ),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_factory_calibration_date',
            field=models.DateField(
                blank=True,
                help_text='Last factory calibration date for this stock item',
                null=True,
                verbose_name='Last Factory Calibration',
            ),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tracklet_status',
            field=models.CharField(
                choices=[
                    ('IN_STOCK', 'In Stock'),
                    ('MISSING', 'Missing'),
                    ('BROKEN', 'Broken'),
                    ('CALIBRATION', 'Calibration'),
                    ('REPAIR', 'Repair'),
                ],
                default='IN_STOCK',
                help_text='Tracklet-specific stock status',
                max_length=32,
                verbose_name='Tracklet Status',
            ),
        ),
        migrations.RunPython(
            map_tracklet_status,
            reverse_code=reverse_tracklet_status,
        ),
    ]
