# Generated by Codex on 2026-02-20

from django.db import migrations, models


def set_stockitem_availability(apps, schema_editor):
    StockItem = apps.get_model('stock', 'StockItem')

    available_codes = {10, 50, 55, 85}
    broken_codes = {55, 60, 65}
    missing_codes = {70}

    to_update = []

    for item in StockItem.objects.all():
        status = item.status

        if status in broken_codes:
            availability = 'BROKEN'
        elif status in missing_codes:
            availability = 'MISSING'
        elif (
            item.quantity <= 0
            or item.sales_order_id is not None
            or item.belongs_to_id is not None
            or item.customer_id is not None
            or item.consumed_by_id is not None
            or item.is_building
            or status not in available_codes
        ):
            availability = 'UNAVAILABLE'
        else:
            availability = 'AVAILABLE'

        if item.availability != availability:
            item.availability = availability
            to_update.append(item)

    if to_update:
        StockItem.objects.bulk_update(to_update, ['availability'])


def unset_stockitem_availability(apps, schema_editor):
    StockItem = apps.get_model('stock', 'StockItem')
    StockItem.objects.all().update(availability='AVAILABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0118_auto_20260205_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='availability',
            field=models.CharField(
                choices=[
                    ('AVAILABLE', 'Available'),
                    ('UNAVAILABLE', 'Unavailable'),
                    ('MISSING', 'Missing'),
                    ('BROKEN', 'Broken'),
                ],
                db_index=True,
                default='AVAILABLE',
                max_length=20,
                verbose_name='Availability',
            ),
        ),
        migrations.RunPython(
            set_stockitem_availability,
            reverse_code=unset_stockitem_availability,
        ),
    ]
