# Generated by Django 5.2.10 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0119_stockitem_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='availability',
            field=models.CharField(
                choices=[
                    ('AVAILABLE', 'Available'),
                    ('RESERVED', 'Reserved'),
                    ('IN_USE', 'In Use'),
                    ('UNAVAILABLE', 'Unavailable'),
                    ('MISSING', 'Missing'),
                    ('BROKEN', 'Broken'),
                ],
                db_index=True,
                default='AVAILABLE',
                max_length=20,
                verbose_name='Availability',
            ),
        ),
    ]
