# Generated by Django 5.2.10 on 2026-02-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0120_stockitem_availability_reserved_in_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                (
                    'description',
                    models.CharField(blank=True, max_length=250, verbose_name='Description'),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='stock.stockcategory',
                        verbose_name='Parent',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Stock item title',
                max_length=150,
                verbose_name='Title',
            ),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stock_items',
                to='stock.stockcategory',
                verbose_name='Category',
            ),
        ),
    ]
