# Generated by Django 5.2.10 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('stock', '0121_stockcategory_and_stockitem_category_title'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE stock_stockitem
            ADD COLUMN IF NOT EXISTS tracklet_status integer;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE stock_stockitem
            ALTER COLUMN tracklet_status TYPE integer
            USING (
                CASE
                    WHEN tracklet_status::text ~ '^[0-9]+$' THEN tracklet_status::integer
                    WHEN UPPER(tracklet_status::text) = 'OK' THEN 10
                    WHEN UPPER(tracklet_status::text) = 'DAMAGED' THEN 55
                    WHEN UPPER(tracklet_status::text) = 'DESTROYED' THEN 60
                    WHEN UPPER(tracklet_status::text) = 'REJECTED' THEN 65
                    WHEN UPPER(tracklet_status::text) = 'LOST' THEN 70
                    ELSE 10
                END
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            UPDATE stock_stockitem
            SET tracklet_status = COALESCE(
                tracklet_status,
                CASE
                    WHEN status::text ~ '^[0-9]+$' THEN status::integer
                    WHEN UPPER(status::text) = 'OK' THEN 10
                    WHEN UPPER(status::text) = 'DAMAGED' THEN 55
                    WHEN UPPER(status::text) = 'DESTROYED' THEN 60
                    WHEN UPPER(status::text) = 'REJECTED' THEN 65
                    WHEN UPPER(status::text) = 'LOST' THEN 70
                    ELSE 10
                END,
                10
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE stock_stockitem
            ALTER COLUMN tracklet_status SET DEFAULT 10;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE stock_stockitem
            ALTER COLUMN tracklet_status SET NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='stockitem',
                    name='tracklet_status',
                    field=models.PositiveIntegerField(
                        db_column='tracklet_status', default=10, editable=False
                    ),
                ),
            ],
        ),
    ]
