# Generated by Django 5.2.12 on 2026-03-18 13:13

import Tracklet.models
import django.core.validators
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0125_stockitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='broken_quantity',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Quantity that is damaged and unusable', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Broken Quantity'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=Tracklet.models.InvenTreeImageMixin.rename_image, variations={'preview': (256, 256), 'thumbnail': (128, 128)}, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='missing_quantity',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Quantity that is missing or unavailable', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Missing Quantity'),
        ),
    ]
