# Generated by Django 5.2.5 on 2026-02-18

import Tracklet.fields
import django.db.models.deletion
import operations.status_codes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('company', '0077_delete_manufacturerpartparameter'),
        ('users', '0015_alter_userprofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', Tracklet.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', verbose_name='Notes')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Planner',
                'verbose_name_plural': 'Planners',
            },
        ),
        migrations.CreateModel(
            name='RentalAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', Tracklet.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', verbose_name='Notes')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('asset_tag', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Asset Tag')),
                ('serial', models.CharField(blank=True, max_length=80, verbose_name='Serial')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Rental Asset',
                'verbose_name_plural': 'Rental Assets',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', Tracklet.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', verbose_name='Notes')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Address')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contact Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_int', models.BigIntegerField(default=0)),
                ('notes', Tracklet.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', verbose_name='Notes')),
                ('reference', models.CharField(blank=True, help_text='Unique reference code', max_length=32, unique=True, verbose_name='Reference')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('rental_start', models.DateTimeField(verbose_name='Rental Start')),
                ('rental_end', models.DateTimeField(verbose_name='Rental End')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Returned Date')),
                ('status', models.IntegerField(choices=operations.status_codes.RentalOrderStatus.items(), default=10, verbose_name='Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_orders', to='company.company', verbose_name='Customer')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_orders', to='users.owner', verbose_name='Responsible')),
            ],
            options={
                'verbose_name': 'Rental Order',
                'verbose_name_plural': 'Rental Orders',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_int', models.BigIntegerField(default=0)),
                ('notes', Tracklet.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', verbose_name='Notes')),
                ('reference', models.CharField(blank=True, help_text='Unique reference code', max_length=32, unique=True, verbose_name='Reference')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('start_datetime', models.DateTimeField(verbose_name='Start DateTime')),
                ('end_datetime', models.DateTimeField(verbose_name='End DateTime')),
                ('late_night_takedown', models.BooleanField(default=False, verbose_name='Late Night Takedown')),
                ('status', models.IntegerField(choices=operations.status_codes.EventStatus.items(), default=10, verbose_name='Status')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.eventtype', verbose_name='Event Type')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='operations.planner', verbose_name='Planner')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='RentalLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', Tracklet.fields.InvenTreeNotesField(blank=True, help_text='Markdown notes (optional)', verbose_name='Notes')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_lines', to='operations.rentalasset', verbose_name='Asset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.rentalorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Rental Line Item',
                'verbose_name_plural': 'Rental Line Items',
            },
        ),
    ]
