# Generated by Django 5.2.5 on 2026-02-18

import Tracklet.fields
import django.db.models.deletion
import operations.status_codes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'notes',
                    Tracklet.fields.InvenTreeNotesField(
                        blank=True,
                        help_text='Markdown notes (optional)',
                        verbose_name='Notes',
                    ),
                ),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Category')),
                ('asset_tag', models.CharField(blank=True, max_length=80, verbose_name='Asset Tag')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Furniture Item',
                'verbose_name_plural': 'Furniture Items',
            },
        ),
        migrations.CreateModel(
            name='EventFurnitureAssignment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'notes',
                    Tracklet.fields.InvenTreeNotesField(
                        blank=True,
                        help_text='Markdown notes (optional)',
                        verbose_name='Notes',
                    ),
                ),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                (
                    'status',
                    models.IntegerField(
                        choices=operations.status_codes.FurnitureAssignmentStatus.items(),
                        default=10,
                        verbose_name='Status',
                    ),
                ),
                (
                    'checked_out_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Checked Out At'
                    ),
                ),
                (
                    'checked_in_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Checked In At'
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='furniture_assignments',
                        to='operations.event',
                        verbose_name='Event',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='event_assignments',
                        to='operations.furnitureitem',
                        verbose_name='Furniture Item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event Furniture Assignment',
                'verbose_name_plural': 'Event Furniture Assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='eventfurnitureassignment',
            constraint=models.UniqueConstraint(
                fields=('event', 'item'), name='event_furniture_item_unique'
            ),
        ),
    ]
