# Generated by Django 5.2.5 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def migrate_furniture_item_to_part(apps, schema_editor):
    Assignment = apps.get_model('operations', 'EventFurnitureAssignment')
    Part = apps.get_model('part', 'Part')
    database_alias = schema_editor.connection.alias

    existing_pairs = set(
        Assignment.objects.using(database_alias)
        .exclude(part_id=None)
        .values_list('event_id', 'part_id')
    )

    assignments = (
        Assignment.objects.using(database_alias)
        .select_related('item')
        .filter(part_id=None, item_id__isnull=False)
    )

    for assignment in assignments:
        item = assignment.item

        if not item:
            continue

        part = (
            Part.objects.using(database_alias)
            .filter(IPN__istartswith='RENTAL-', name__iexact=item.name)
            .order_by('pk')
            .first()
        )

        if part is None and item.name:
            part = (
                Part.objects.using(database_alias)
                .filter(IPN__istartswith='RENTAL-', name__icontains=item.name.strip())
                .order_by('pk')
                .first()
            )

        if part is None:
            continue

        pair_key = (assignment.event_id, part.pk)

        if pair_key in existing_pairs:
            continue

        assignment.part_id = part.pk
        assignment.save(update_fields=['part'])
        existing_pairs.add(pair_key)


class Migration(migrations.Migration):
    dependencies = [
        ('operations', '0002_event_furniture'),
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfurnitureassignment',
            name='part',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='event_furniture_assignments',
                to='part.part',
                verbose_name='Part',
            ),
        ),
        migrations.AlterField(
            model_name='eventfurnitureassignment',
            name='item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='event_assignments',
                to='operations.furnitureitem',
                verbose_name='Furniture Item',
            ),
        ),
        migrations.RunPython(
            migrate_furniture_item_to_part,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='eventfurnitureassignment',
            name='event_furniture_item_unique',
        ),
        migrations.AddConstraint(
            model_name='eventfurnitureassignment',
            constraint=models.UniqueConstraint(
                condition=Q(item__isnull=False),
                fields=('event', 'item'),
                name='event_furniture_item_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='eventfurnitureassignment',
            constraint=models.UniqueConstraint(
                condition=Q(part__isnull=False),
                fields=('event', 'part'),
                name='event_furniture_part_unique',
            ),
        ),
    ]
