# Generated by Django 5.2.10 on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_eventfurnitureassignment_part'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventfurnitureassignment',
            name='event_furniture_item_unique',
        ),
        migrations.RemoveConstraint(
            model_name='eventfurnitureassignment',
            name='event_furniture_part_unique',
        ),
    ]
