# Generated by Django 5.2.11 on 2026-02-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion

import generic.states.fields
import generic.states.validators
import Tracklet.status_codes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0015_alter_userprofile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Event title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Event description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status_custom_key",
                    generic.states.fields.ExtraInvenTreeCustomStatusModelField(
                        blank=True,
                        default=None,
                        help_text="Additional status information for this item",
                        null=True,
                        verbose_name="Custom status key",
                        validators=[
                            generic.states.validators.CustomStatusCodeValidator(
                                status_class=Tracklet.status_codes.EventStatus
                            ),
                        ],
                    ),
                ),
                (
                    "status",
                    generic.states.fields.InvenTreeCustomStatusModelField(
                        choices=Tracklet.status_codes.EventStatus.items(),
                        default=10,
                        help_text="Event status",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            generic.states.validators.CustomStatusCodeValidator(
                                status_class=Tracklet.status_codes.EventStatus
                            ),
                        ],
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Event start date", verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Event end date",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date the event was created",
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        help_text="User or group responsible for this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.owner",
                        verbose_name="Responsible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
