# Generated by Django 5.2.11 on 2026-02-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="late_night_takedown",
            field=models.BooleanField(
                default=False,
                help_text="Late-night takedown required",
                verbose_name="Late-night takedown",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="planner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who planned this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Planner",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Event venue",
                max_length=255,
                verbose_name="Venue",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unspecified"),
                    ("conference", "Conference"),
                    ("party", "Party"),
                    ("meeting", "Meeting"),
                    ("wedding", "Wedding"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Type of event",
                max_length=32,
                verbose_name="Event Type",
            ),
        ),
    ]

