# Generated by Django 5.2.5 on 2026-02-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import Tracklet.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0118_auto_20260205_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                (
                    'description',
                    models.TextField(blank=True, default='', verbose_name='Description'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('FUTURE', 'Future'),
                            ('ONGOING', 'Ongoing'),
                            ('PAST', 'Past'),
                        ],
                        default='FUTURE',
                        max_length=16,
                        verbose_name='Status',
                    ),
                ),
                (
                    'start_date',
                    models.DateField(blank=True, null=True, verbose_name='Start Date'),
                ),
                (
                    'end_date',
                    models.DateField(blank=True, null=True, verbose_name='End Date'),
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStockAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'quantity',
                    Tracklet.fields.RoundingDecimalField(
                        decimal_places=5,
                        help_text='Quantity of stock item allocated to project',
                        max_digits=15,
                        verbose_name='Quantity',
                    ),
                ),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='allocations',
                        to='projects.project',
                        verbose_name='Project',
                    ),
                ),
                (
                    'stock_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_allocations',
                        to='stock.stockitem',
                        verbose_name='Stock Item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project Stock Allocation',
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectstockallocation',
            constraint=models.UniqueConstraint(
                fields=('project', 'stock_item'),
                name='projects_unique_project_stock_item',
            ),
        ),
    ]
