# Generated by Django 5.2.5 on 2026-02-17

from django.db import migrations

import Tracklet.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=Tracklet.fields.InvenTreeNotesField(
                blank=True,
                help_text='Markdown notes (optional)',
                max_length=50000,
                null=True,
                verbose_name='Notes',
            ),
        ),
    ]
