# Generated by Django 5.2.5 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models

import Tracklet.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0118_auto_20260205_1218'),
        ('projects', '0002_project_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInstrument',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    Tracklet.fields.RoundingDecimalField(
                        decimal_places=5,
                        default=1,
                        help_text='Quantity of stock item tracked as project instrument',
                        max_digits=15,
                        verbose_name='Quantity',
                    ),
                ),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='instruments',
                        to='projects.project',
                        verbose_name='Project',
                    ),
                ),
                (
                    'stock_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_instruments',
                        to='stock.stockitem',
                        verbose_name='Stock Item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Project Instrument',
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectinstrument',
            constraint=models.UniqueConstraint(
                fields=('project', 'stock_item'),
                name='projects_unique_project_instrument_stock_item',
            ),
        ),
    ]
