# Generated by Django 5.2.10 on 2026-02-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_auto_20251203_1244'),
        ('projects', '0003_projectinstrument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('BROKEN_INVENTORY', 'Broken Inventory')], default='BROKEN_INVENTORY', max_length=32, verbose_name='Report Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_reports', to='common.attachment', verbose_name='Attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Report',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('manufacture', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('sn', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('specification', models.CharField(blank=True, default='', max_length=250)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('located', models.CharField(blank=True, default='', max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.projectreport', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Project Report Item',
                'ordering': ['pk'],
            },
        ),
    ]
