# Generated by Django 5.2.11 on 2026-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreport',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='projectreportitem',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectreportitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
