# Generated by Django 5.2.11 on 2026-02-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_projectreport_metadata_and_more'),
        ('projects', '0009_backfill_project_location_ref'),
    ]

    operations = [
    ]
