# Generated by Django 5.2.12 on 2026-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projectinstrument_calibration_fields'),
        ('stock', '0126_alter_stockitem_broken_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectinstrument',
            name='projects_unique_project_instrument_stock_item',
        ),
        migrations.AddField(
            model_name='projectinstrument',
            name='release_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RETURNED', 'Returned'), ('BROKEN', 'Broken'), ('MISSING', 'Missing')], default='PENDING', max_length=16, verbose_name='Release Status'),
        ),
        migrations.AddField(
            model_name='projectinstrument',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Released At'),
        ),
        migrations.AddConstraint(
            model_name='projectinstrument',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('project', 'stock_item'), name='projects_unique_project_instrument_stock_item'),
        ),
    ]
