# Generated by Django 5.2.12 on 2026-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_projectinstrument_projects_unique_project_instrument_stock_item_and_more'),
        ('stock', '0126_alter_stockitem_broken_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectinstrument',
            name='projects_unique_project_instrument_stock_item',
        ),
        migrations.AddConstraint(
            model_name='projectinstrument',
            constraint=models.UniqueConstraint(fields=('project', 'stock_item'), name='projects_unique_project_instrument_stock_item'),
        ),
    ]
