"""Create the fictional, repeatable Tracklet public portfolio dataset."""

from __future__ import annotations

import os
from datetime import date, timedelta

from django.contrib.auth.models import Group, User
from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from common.models import Parameter, ParameterTemplate
from company.models import Company
from operations.models import (
    Event,
    EventFurnitureAssignment,
    EventType,
    Planner,
    RentalLineItem,
    RentalOrder,
    Venue,
)
from operations.status_codes import (
    EventStatus,
    FurnitureAssignmentStatus,
    RentalOrderStatus,
)
from part.models import Part, PartCategory, PartCategoryParameterTemplate
from stock.models import StockCategory, StockItem, StockLocation
from stock.status_codes import StockStatus
from users.models import Owner, RuleSet
from users.ruleset import RuleSetEnum
from users.tasks import update_group_roles

DEMO_MARKER = 'Generated by the Tracklet fictional public-demo seed.'
DEMO_GROUP = 'Tracklet Demo Viewers'
DEMO_LOCATION_ROOT = 'Demo Instrumentation Lab'

CATEGORIES = [
    'Pressure Sensors',
    'Temperature Sensors',
    'Flow Sensors',
    'Data Acquisition',
    'Cameras',
    'Networking Equipment',
    'Measurement Equipment',
    'Cables / Accessories',
    'Power Equipment',
    'Field Equipment',
]

LOCATIONS = [
    'Main Instrument Room',
    'Electronics Lab',
    'Storage Room A',
    'Storage Room B',
    'Calibration Bench',
    'Field Equipment Rack',
    'Networking Cabinet',
    'Camera Storage',
    'Mobile Equipment Area',
]

MANUFACTURERS = [
    'Northstar Instruments',
    'BluePeak Systems',
    'Vertex Measurement',
    'Helix Technologies',
    'Meridian Sensors',
    'Atlas Scientific Systems',
]

CUSTOMERS = [
    'Aurora Field Research',
    'Clearwater Model Works',
    'Summit Applied Studies',
]

# category, fictional manufacturer, model, serial suffix, default location
INVENTORY = [
    (
        'Pressure Sensors',
        'Northstar Instruments',
        'PX-200 Pressure Transducer',
        'PS-001',
        'Calibration Bench',
    ),
    (
        'Pressure Sensors',
        'Northstar Instruments',
        'PX-240 Differential Sensor',
        'PS-002',
        'Main Instrument Room',
    ),
    (
        'Pressure Sensors',
        'Meridian Sensors',
        'BaroNode B60',
        'PS-003',
        'Main Instrument Room',
    ),
    (
        'Pressure Sensors',
        'Vertex Measurement',
        'HydraPress P12',
        'PS-004',
        'Field Equipment Rack',
    ),
    (
        'Temperature Sensors',
        'Meridian Sensors',
        'TempNode T80',
        'TS-001',
        'Calibration Bench',
    ),
    (
        'Temperature Sensors',
        'BluePeak Systems',
        'ThermaProbe TP4',
        'TS-002',
        'Main Instrument Room',
    ),
    (
        'Temperature Sensors',
        'Helix Technologies',
        'CryoSense C10',
        'TS-003',
        'Storage Room A',
    ),
    (
        'Flow Sensors',
        'BluePeak Systems',
        'AquaSense Flow Meter',
        'FS-001',
        'Calibration Bench',
    ),
    (
        'Flow Sensors',
        'Atlas Scientific Systems',
        'StreamGauge F20',
        'FS-002',
        'Field Equipment Rack',
    ),
    (
        'Flow Sensors',
        'Meridian Sensors',
        'MicroFlow M8',
        'FS-003',
        'Main Instrument Room',
    ),
    (
        'Data Acquisition',
        'Vertex Measurement',
        'DAQ Station X4',
        'DAQ-001',
        'Electronics Lab',
    ),
    (
        'Data Acquisition',
        'Vertex Measurement',
        'DAQ Station X8',
        'DAQ-002',
        'Electronics Lab',
    ),
    (
        'Data Acquisition',
        'Helix Technologies',
        'SignalHub S16',
        'DAQ-003',
        'Electronics Lab',
    ),
    (
        'Data Acquisition',
        'BluePeak Systems',
        'FieldLogger L6',
        'DAQ-004',
        'Mobile Equipment Area',
    ),
    ('Cameras', 'Helix Technologies', 'VisionCam C200', 'CAM-001', 'Camera Storage'),
    ('Cameras', 'Helix Technologies', 'VisionCam C240', 'CAM-002', 'Camera Storage'),
    (
        'Cameras',
        'Atlas Scientific Systems',
        'MotionScope M12',
        'CAM-003',
        'Camera Storage',
    ),
    (
        'Networking Equipment',
        'BluePeak Systems',
        'FieldRouter R8',
        'NET-001',
        'Networking Cabinet',
    ),
    (
        'Networking Equipment',
        'Northstar Instruments',
        'Telemetry Bridge T4',
        'NET-002',
        'Networking Cabinet',
    ),
    (
        'Networking Equipment',
        'Helix Technologies',
        'RuggedSwitch S10',
        'NET-003',
        'Networking Cabinet',
    ),
    (
        'Measurement Equipment',
        'Vertex Measurement',
        'Laser Distance Meter L50',
        'ME-001',
        'Main Instrument Room',
    ),
    (
        'Measurement Equipment',
        'Atlas Scientific Systems',
        'Optical Level O20',
        'ME-002',
        'Calibration Bench',
    ),
    (
        'Measurement Equipment',
        'Meridian Sensors',
        'Vibration Meter V7',
        'ME-003',
        'Main Instrument Room',
    ),
    (
        'Cables / Accessories',
        'BluePeak Systems',
        'Shielded Sensor Cable 20 m',
        'CAB-001',
        'Storage Room A',
    ),
    (
        'Cables / Accessories',
        'Northstar Instruments',
        'DAQ Breakout Harness',
        'CAB-002',
        'Storage Room A',
    ),
    (
        'Cables / Accessories',
        'Vertex Measurement',
        'Field Connector Kit',
        'CAB-003',
        'Storage Room B',
    ),
    (
        'Power Equipment',
        'Helix Technologies',
        'Portable Power Hub P6',
        'PWR-001',
        'Storage Room B',
    ),
    (
        'Power Equipment',
        'Atlas Scientific Systems',
        'Isolated Supply I24',
        'PWR-002',
        'Electronics Lab',
    ),
    (
        'Power Equipment',
        'BluePeak Systems',
        'Field Battery Pack B40',
        'PWR-003',
        'Mobile Equipment Area',
    ),
    (
        'Field Equipment',
        'Atlas Scientific Systems',
        'Survey Tripod ST3',
        'FE-001',
        'Field Equipment Rack',
    ),
    (
        'Field Equipment',
        'Meridian Sensors',
        'Weather Enclosure W12',
        'FE-002',
        'Field Equipment Rack',
    ),
    (
        'Field Equipment',
        'Northstar Instruments',
        'Portable Mast M6',
        'FE-003',
        'Mobile Equipment Area',
    ),
]


class Command(BaseCommand):
    """Create or refresh the public portfolio demo dataset."""

    help = 'Create an idempotent, entirely fictional Tracklet public-demo dataset'

    def add_arguments(self, parser):
        parser.add_argument(
            '--reset',
            action='store_true',
            help='Remove only objects created by this command before reseeding',
        )

    @transaction.atomic
    def handle(self, *args, **options):
        password = os.environ.get('TRACKLET_DEMO_PASSWORD', '')
        if not password:
            raise CommandError(
                'Set TRACKLET_DEMO_PASSWORD to a clearly fake, changeable demo password.'
            )

        if options['reset']:
            self._remove_demo_data()

        user = self._create_demo_user(password)
        part_categories, stock_categories = self._create_categories()
        locations = self._create_locations()
        companies = self._create_companies()
        parts, stock_items = self._create_inventory(
            part_categories, stock_categories, locations
        )
        calibration_counts = self._create_calibration_data(parts, part_categories)
        events, assignments = self._create_events(parts)
        rentals, rental_lines = self._create_rentals(stock_items, companies, user)

        # Recalculate canonical availability only after reservations exist.
        for item in stock_items.values():
            if item.status in [
                StockStatus.LOST.value,
                StockStatus.DAMAGED.value,
                StockStatus.DESTROYED.value,
                StockStatus.REJECTED.value,
            ]:
                availability = item.infer_availability()
            elif item.serial in {'DEMO-PWR-001', 'DEMO-PWR-002'}:
                availability = StockItem.Availability.UNAVAILABLE
            else:
                availability = item.infer_availability()

            StockItem.objects.filter(pk=item.pk).update(availability=availability)

        counts = {
            'instruments': len(stock_items),
            'categories': len(stock_categories),
            'locations': StockLocation.objects.filter(
                name__in=[DEMO_LOCATION_ROOT, *LOCATIONS]
            ).count(),
            'events': len(events),
            'reservations': len(assignments),
            'rentals': len(rentals),
            'rental lines': len(rental_lines),
        }
        summary = ', '.join(f'{key}={value}' for key, value in counts.items())
        calibration = ', '.join(
            f'{key}={value}' for key, value in calibration_counts.items()
        )
        self.stdout.write(self.style.SUCCESS(f'Demo seed complete: {summary}'))
        self.stdout.write(f'Calibration parameters: {calibration}')
        self.stdout.write(
            'Demo account: demo (non-staff, non-superuser, view-only roles)'
        )

    def _remove_demo_data(self):
        RentalOrder.objects.filter(reference__startswith='DEMO-RN-').delete()
        Event.objects.filter(reference__startswith='DEMO-EV-').delete()
        StockItem.objects.filter(serial__startswith='DEMO-').delete()
        Part.objects.filter(IPN__startswith='DEMO-').delete()

        for name in reversed(LOCATIONS):
            StockLocation.objects.filter(
                name=name, parent__name=DEMO_LOCATION_ROOT
            ).delete()
        StockLocation.objects.filter(name=DEMO_LOCATION_ROOT).delete()

        for name in CATEGORIES:
            PartCategory.objects.filter(
                name=name, parent__name='Demo Equipment'
            ).delete()
            StockCategory.objects.filter(name=name).delete()
        PartCategory.objects.filter(name='Demo Equipment').delete()

        Company.objects.filter(name__in=[*MANUFACTURERS, *CUSTOMERS]).delete()
        Planner.objects.filter(name='Demo Operations Team').delete()
        Venue.objects.filter(
            name__in=['Demo North Basin', 'Demo Hydraulics Hall', 'Demo Coastal Annex']
        ).delete()
        EventType.objects.filter(
            name__in=['Demo Field Study', 'Demo Lab Test', 'Demo Validation']
        ).delete()
        ParameterTemplate.objects.filter(metadata__tracklet_demo=True).delete()
        User.objects.filter(username='demo').delete()
        Group.objects.filter(name=DEMO_GROUP).delete()

    def _create_demo_user(self, password):
        group, _ = Group.objects.get_or_create(name=DEMO_GROUP)
        update_group_roles(group)

        view_roles = {
            RuleSetEnum.PART_CATEGORY,
            RuleSetEnum.PART,
            RuleSetEnum.STOCK_LOCATION,
            RuleSetEnum.STOCK,
            RuleSetEnum.SALES_ORDER,
        }
        for ruleset in RuleSet.objects.filter(group=group):
            ruleset.can_view = ruleset.name in view_roles
            ruleset.can_add = False
            ruleset.can_change = False
            ruleset.can_delete = False
            ruleset.save()
        update_group_roles(group)

        user, _ = User.objects.update_or_create(
            username='demo',
            defaults={
                'first_name': 'Demo',
                'last_name': 'Visitor',
                'email': 'demo@example.invalid',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
            },
        )
        user.groups.set([group])
        user.set_password(password)
        user.save()
        return user

    def _create_categories(self):
        root, _ = PartCategory.objects.update_or_create(
            name='Demo Equipment',
            parent=None,
            defaults={
                'description': DEMO_MARKER,
                'structural': True,
                'metadata': {'tracklet_demo': True},
            },
        )
        part_categories = {}
        stock_categories = {}
        for name in CATEGORIES:
            part_categories[name], _ = PartCategory.objects.update_or_create(
                name=name,
                parent=root,
                defaults={
                    'description': f'{name}. {DEMO_MARKER}',
                    'structural': False,
                    'metadata': {'tracklet_demo': True},
                },
            )
            stock_categories[name], _ = StockCategory.objects.update_or_create(
                name=name,
                parent=None,
                defaults={
                    'description': f'{name}. {DEMO_MARKER}',
                    'metadata': {'tracklet_demo': True},
                },
            )
        return part_categories, stock_categories

    def _create_locations(self):
        root, _ = StockLocation.objects.update_or_create(
            name=DEMO_LOCATION_ROOT,
            parent=None,
            defaults={
                'description': DEMO_MARKER,
                'structural': True,
                'metadata': {'tracklet_demo': True},
            },
        )
        locations = {}
        for name in LOCATIONS:
            locations[name], _ = StockLocation.objects.update_or_create(
                name=name,
                parent=root,
                defaults={
                    'description': f'Fictional demo storage area. {DEMO_MARKER}',
                    'structural': False,
                    'metadata': {'tracklet_demo': True},
                },
            )
        return locations

    def _create_companies(self):
        companies = {}
        for name in MANUFACTURERS:
            companies[name], _ = Company.objects.update_or_create(
                name=name,
                email=None,
                defaults={
                    'description': f'Fictional manufacturer used only in the Tracklet demo. {DEMO_MARKER}',
                    'active': True,
                    'is_customer': False,
                    'is_supplier': False,
                    'is_manufacturer': True,
                    'metadata': {'tracklet_demo': True},
                },
            )
        for name in CUSTOMERS:
            companies[name], _ = Company.objects.update_or_create(
                name=name,
                email=None,
                defaults={
                    'description': f'Fictional rental customer used only in the Tracklet demo. {DEMO_MARKER}',
                    'active': True,
                    'is_customer': True,
                    'is_supplier': False,
                    'is_manufacturer': False,
                    'metadata': {'tracklet_demo': True},
                },
            )
        return companies

    def _create_inventory(self, part_categories, stock_categories, locations):
        parts = {}
        stock_items = {}

        repair_serials = {'DEMO-PWR-001', 'DEMO-PWR-002'}
        missing_serials = {'DEMO-PWR-003'}
        broken_serials = {'DEMO-FE-001', 'DEMO-FE-002'}
        found_serials = {'DEMO-FE-003'}

        for category, manufacturer, name, suffix, location in INVENTORY:
            serial = f'DEMO-{suffix}'
            part, _ = Part.objects.update_or_create(
                IPN=serial,
                revision=None,
                defaults={
                    'name': name,
                    'description': f'{manufacturer} fictional demo instrument',
                    'keywords': f'demo, equipment, {category}, {manufacturer}',
                    'category': part_categories[category],
                    'default_location': locations[location],
                    'trackable': True,
                    'testable': category
                    not in {'Cables / Accessories', 'Power Equipment'},
                    'purchaseable': False,
                    'salable': False,
                    'active': True,
                    'metadata': {
                        'tracklet_demo': True,
                        'fictional_manufacturer': manufacturer,
                    },
                },
            )
            parts[serial] = part

            status = StockStatus.OK.value
            availability = StockItem.Availability.AVAILABLE
            notes = DEMO_MARKER
            if serial in repair_serials:
                status = StockStatus.ATTENTION.value
                availability = StockItem.Availability.UNAVAILABLE
                notes = f'Queued for fictional workshop inspection. {DEMO_MARKER}'
            elif serial in missing_serials:
                status = StockStatus.LOST.value
                availability = StockItem.Availability.MISSING
                notes = (
                    f'Marked missing during a fictional demo stocktake. {DEMO_MARKER}'
                )
            elif serial in broken_serials:
                status = StockStatus.DAMAGED.value
                availability = StockItem.Availability.BROKEN
                notes = f'Removed from service in the fictional demo. {DEMO_MARKER}'
            elif serial in found_serials:
                status = StockStatus.RETURNED.value
                notes = f'Recently found and returned to storage. {DEMO_MARKER}'

            item, _ = StockItem.objects.update_or_create(
                part=part,
                serial=serial,
                defaults={
                    'title': name,
                    'location': locations[location],
                    'category': stock_categories[category],
                    'quantity': 1,
                    'status': status,
                    'availability': availability,
                    'notes': notes,
                    'metadata': {'tracklet_demo': True},
                },
            )
            stock_items[serial] = item

        return parts, stock_items

    def _create_calibration_data(self, parts, part_categories):
        content_type = ContentType.objects.get_for_model(Part)
        templates = {}
        template_specs = {
            'required': ('Calibration Required', '', True),
            'interval': ('Calibration Interval', 'days', False),
            'last': ('Calibration Last Completed', '', False),
            'due': ('Calibration Next Due', '', False),
        }
        for key, (name, units, checkbox) in template_specs.items():
            templates[key], _ = ParameterTemplate.objects.update_or_create(
                name=name,
                defaults={
                    'model_type': content_type,
                    'description': f'Fictional public-demo calibration field. {DEMO_MARKER}',
                    'units': units,
                    'checkbox': checkbox,
                    'enabled': True,
                    'metadata': {'tracklet_demo': True},
                },
            )

        calibrated_categories = {
            'Pressure Sensors',
            'Temperature Sensors',
            'Flow Sensors',
            'Data Acquisition',
            'Measurement Equipment',
            'Field Equipment',
        }
        for name, category in part_categories.items():
            required = name in calibrated_categories
            PartCategoryParameterTemplate.objects.update_or_create(
                category=category,
                template=templates['required'],
                defaults={'default_value': str(required)},
            )
            if required:
                PartCategoryParameterTemplate.objects.update_or_create(
                    category=category,
                    template=templates['interval'],
                    defaults={'default_value': '365'},
                )

        today = date.today()
        counts = {'healthy': 0, 'due_soon': 0, 'overdue': 0, 'not_required': 0}
        required_index = 0
        for _serial, part in parts.items():
            category = part.category.name
            required = category in calibrated_categories
            values = {'required': str(required)}
            if required:
                state = ['healthy', 'due_soon', 'overdue'][required_index % 3]
                required_index += 1
                if state == 'healthy':
                    last, due = today - timedelta(days=45), today + timedelta(days=320)
                elif state == 'due_soon':
                    last, due = today - timedelta(days=350), today + timedelta(days=15)
                else:
                    last, due = today - timedelta(days=390), today - timedelta(days=25)
                values.update({
                    'interval': '365',
                    'last': last.isoformat(),
                    'due': due.isoformat(),
                })
                counts[state] += 1
            else:
                counts['not_required'] += 1

            for key, value in values.items():
                Parameter.objects.update_or_create(
                    model_type=content_type,
                    model_id=part.pk,
                    template=templates[key],
                    defaults={
                        'data': value,
                        'note': DEMO_MARKER,
                        'metadata': {'tracklet_demo': True},
                    },
                )
        return counts

    def _create_events(self, parts):
        now = timezone.now()
        event_types = {}
        for name in ['Demo Field Study', 'Demo Lab Test', 'Demo Validation']:
            event_types[name], _ = EventType.objects.update_or_create(
                name=name, defaults={'description': DEMO_MARKER, 'active': True}
            )
        venues = {}
        for name in ['Demo North Basin', 'Demo Hydraulics Hall', 'Demo Coastal Annex']:
            venues[name], _ = Venue.objects.update_or_create(
                name=name,
                defaults={
                    'address': 'Fictional demo venue',
                    'contact_name': '',
                    'contact_email': '',
                    'active': True,
                    'notes': DEMO_MARKER,
                },
            )
        planner, _ = Planner.objects.update_or_create(
            name='Demo Operations Team',
            defaults={
                'email': 'operations@example.invalid',
                'phone': '',
                'active': True,
                'notes': DEMO_MARKER,
            },
        )

        specs = [
            (
                'DEMO-EV-001',
                'River Flow Study',
                'Demo Field Study',
                'Demo North Basin',
                -60,
                -58,
                EventStatus.COMPLETED.value,
            ),
            (
                'DEMO-EV-002',
                'Wave Basin Test A',
                'Demo Lab Test',
                'Demo Hydraulics Hall',
                -16,
                -14,
                EventStatus.COMPLETED.value,
            ),
            (
                'DEMO-EV-003',
                'Coastal Sensor Trial',
                'Demo Field Study',
                'Demo Coastal Annex',
                -1,
                1,
                EventStatus.IN_PROGRESS.value,
            ),
            (
                'DEMO-EV-004',
                'Hydraulic Model Calibration',
                'Demo Lab Test',
                'Demo Hydraulics Hall',
                -0.2,
                0.8,
                EventStatus.IN_PROGRESS.value,
            ),
            (
                'DEMO-EV-005',
                'Channel Monitoring Demo',
                'Demo Field Study',
                'Demo North Basin',
                5,
                7,
                EventStatus.SCHEDULED.value,
            ),
            (
                'DEMO-EV-006',
                'Instrument Validation Week',
                'Demo Validation',
                'Demo Hydraulics Hall',
                14,
                19,
                EventStatus.SCHEDULED.value,
            ),
            (
                'DEMO-EV-007',
                'Field Equipment Trial',
                'Demo Field Study',
                'Demo Coastal Annex',
                30,
                32,
                EventStatus.SCHEDULED.value,
            ),
            (
                'DEMO-EV-008',
                'Telemetry Integration Exercise',
                'Demo Validation',
                'Demo North Basin',
                45,
                47,
                EventStatus.SCHEDULED.value,
            ),
        ]
        events = {}
        for reference, title, kind, venue, start, end, status in specs:
            events[reference], _ = Event.objects.update_or_create(
                reference=reference,
                defaults={
                    'title': title,
                    'event_type': event_types[kind],
                    'venue': venues[venue],
                    'planner': planner,
                    'start_datetime': now + timedelta(days=start),
                    'end_datetime': now + timedelta(days=end),
                    'status': status,
                    'notes': DEMO_MARKER,
                },
            )

        assignments = []
        links = [
            ('DEMO-EV-001', 'DEMO-ME-002', FurnitureAssignmentStatus.RETURNED.value),
            ('DEMO-EV-001', 'DEMO-FE-003', FurnitureAssignmentStatus.RETURNED.value),
            ('DEMO-EV-002', 'DEMO-DAQ-001', FurnitureAssignmentStatus.RETURNED.value),
            ('DEMO-EV-002', 'DEMO-CAM-003', FurnitureAssignmentStatus.RETURNED.value),
            ('DEMO-EV-003', 'DEMO-PS-004', FurnitureAssignmentStatus.IN_USE.value),
            ('DEMO-EV-003', 'DEMO-TS-001', FurnitureAssignmentStatus.IN_USE.value),
            ('DEMO-EV-004', 'DEMO-FS-001', FurnitureAssignmentStatus.IN_USE.value),
            ('DEMO-EV-005', 'DEMO-FS-002', FurnitureAssignmentStatus.RESERVED.value),
            ('DEMO-EV-005', 'DEMO-FS-003', FurnitureAssignmentStatus.RESERVED.value),
            ('DEMO-EV-006', 'DEMO-DAQ-002', FurnitureAssignmentStatus.RESERVED.value),
            ('DEMO-EV-007', 'DEMO-DAQ-003', FurnitureAssignmentStatus.RESERVED.value),
            ('DEMO-EV-008', 'DEMO-DAQ-004', FurnitureAssignmentStatus.RESERVED.value),
        ]
        for event_ref, serial, status in links:
            assignment, _ = EventFurnitureAssignment.objects.update_or_create(
                event=events[event_ref],
                part=parts[serial],
                defaults={
                    'item': None,
                    'quantity': 1,
                    'status': status,
                    'notes': DEMO_MARKER,
                },
            )
            assignments.append(assignment)
        return events, assignments

    def _create_rentals(self, stock_items, companies, user):
        now = timezone.now()
        responsible = Owner.get_owner(user)
        specs = [
            (
                'DEMO-RN-001',
                'Aurora Field Research',
                -40,
                -35,
                RentalOrderStatus.RETURNED.value,
            ),
            (
                'DEMO-RN-002',
                'Clearwater Model Works',
                -1,
                5,
                RentalOrderStatus.ACTIVE.value,
            ),
            (
                'DEMO-RN-003',
                'Summit Applied Studies',
                10,
                15,
                RentalOrderStatus.DRAFT.value,
            ),
            (
                'DEMO-RN-004',
                'Aurora Field Research',
                -10,
                -3,
                RentalOrderStatus.OVERDUE.value,
            ),
        ]
        rentals = {}
        for reference, customer, start, end, status in specs:
            rentals[reference], _ = RentalOrder.objects.update_or_create(
                reference=reference,
                defaults={
                    'customer': companies[customer],
                    'rental_start': now + timedelta(days=start),
                    'rental_end': now + timedelta(days=end),
                    'returned_date': now + timedelta(days=end)
                    if status == RentalOrderStatus.RETURNED.value
                    else None,
                    'status': status,
                    'responsible': responsible,
                    'notes': DEMO_MARKER,
                },
            )

        lines = []
        links = [
            ('DEMO-RN-001', 'DEMO-CAM-001'),
            ('DEMO-RN-001', 'DEMO-NET-001'),
            ('DEMO-RN-002', 'DEMO-CAM-002'),
            ('DEMO-RN-002', 'DEMO-NET-002'),
            ('DEMO-RN-003', 'DEMO-NET-003'),
            ('DEMO-RN-003', 'DEMO-ME-001'),
            ('DEMO-RN-004', 'DEMO-ME-003'),
            ('DEMO-RN-004', 'DEMO-CAB-001'),
        ]
        for order_ref, serial in links:
            line, _ = RentalLineItem.objects.update_or_create(
                order=rentals[order_ref],
                asset=stock_items[serial],
                defaults={'quantity': 1, 'notes': DEMO_MARKER},
            )
            lines.append(line)
        return rentals, lines
