# Generated by Django 5.2.11 on 2026-03-16 05:19

import Tracklet.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0146_auto_20251203_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=Tracklet.models.InvenTreeImageMixin.rename_image, variations={'preview': (512, 512), 'thumbnail': (128, 128)}, verbose_name='Image'),
        ),
    ]
